Backport Java 8 compile time break workaround.
Required for building host libraries with OpenJDK 8.

Without this, trying to build with Java 8 fails with:
external/guava/guava/src/com/google/common/reflect/Types.java:317:
error: TypeVariableImpl is not abstract and does not override abstract method getAnnotatedBounds() in TypeVariable
 private static final class TypeVariableImpl<D extends GenericDeclaration>

Backport of https://github.com/google/guava/commit/f4aa25e74a9466c2f93a2147a7cf9b01850dd41f
See https://github.com/google/guava/issues/1738

Bug: 23074347
Change-Id: I35adc64a339055e1e426af2aa3a41058f9948984

Conflicts:
	guava/src/com/google/common/reflect/Types.java